arb-dir: lib/l10n
template-arb-file: app_ar.arb
output-class: SimpleLocalizations
output-localization-file: simple_localizations.dart
untranslated-messages-file: untranslated.json
output-dir: lib/src/gen_l10n
synthetic-package: false
