name: simple
description: Collection of extension methods to make your code simple , clean and fast
version: 1.0.4
homepage: https://github.com/mo-ah-dawood/simple
repository: https://github.com/mo-ah-dawood/simple
issue_tracker: https://github.com/mo-ah-dawood/simple/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
