name: simple_dart
description: Collection of extension methods to make your code simple , clean and fast
version: 1.0.0
homepage: https://github.com/mo-ah-dawood/simple/simple_dart
repository: https://github.com/mo-ah-dawood/simple
issue_tracker: https://github.com/mo-ah-dawood/simple/issues

environment:
  sdk: ">=2.12.0 <3.0.0"



dev_dependencies:
  test: any
